---
# playbooks/site.yml
# Master Infrastructure-as-Code Configuration Management Playbook
# Architected by: Vinny Firas Bsoul (Linux Infrastructure Engineer)

- name: Stage 1 — Baseline Operating System Configuration
  hosts: all_vms
  become: true
  gather_facts: true

  tags:
    - os-config

  roles:
    - os_configuration


- name: Stage 2 — Performance Optimization
  hosts: loadbalancers, webservers
  become: true
  gather_facts: false

  tags:
    - performance

  roles:
    - performance

- name: Stage 3 - Security Enforcement & Hardening
  hosts: all_vms
  become: true
  gather_facts: false

  tags:
    - security

  roles:
    - security

- name: Stage 4 - Identity & Access Administration
  hosts: all_vms
  become: true
  gather_facts: false

  tags:
    - useradmin

  roles:
    - useradmin

- name: Stage 5 - Application Delivery Layer
  hosts: loadbalancers
  become: true
  gather_facts: false

  tags:
    - lb
    - proxy

  roles:
    - os_configuration
    - security
    - nginx_lb
