---
- name: Upgrade all Linux packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Show OS version
  ansible.builtin.debug:
    msg:
      - "Host: {{ inventory_hostname }}"
      - "Distribution: {{ ansible_distribution }}"
      - "Version: {{ ansible_distribution_version }}"
