[all_vms]
ansible-vm3
loadbalancer
webserver

[webservers]
webserver

[loadbalancers]
loadbalancer

[control_plane]
loadbalancer ansible_host=192.168.100.6

[worker_nodes]
webserver ansible_host=192.168.100.5

[k3s_cluster:children]
worker_nodes
control_plane


[control]
localhost ansible_connection=local

[k3s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
