apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-webapp
  namespace: default
  labels:
    app: custom-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-web
  template:
    metadata:
      labels:
        app: custom-web
    spec:
      containers:
      - name: web-container
        image: ghcr.io/fbsoul/ansible/my-web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/info
      volumes:
      - name: config-volume
        configMap:
          name: webapp-config

